name: Frontend
description: Changes in Frontend
title: "[Frontend] country name>"
labels: [Frontend]
body:
  - type: textarea
    id: info
    attributes:
      label: Details
    validations:
      required: true
